version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.322
    steps:
      - checkout
      - run:
          name: "Grant execute permission for gradlew"
          command: "chmod +x gradlew"
      - run:
          name: "Build and Test"
          command: "./gradlew clean build jacocoMergedReport"
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: build/reports/jacocoMergedReport/jacocoMergedReport.xml
          destination: coverage
      - persist_to_workspace:
          root: applications/app-service/build
          paths:
            - libs
  publish:
    docker:
      - image: cimg/base:2022.05
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/libs/
          destination: Artifact
          

workflows:
  version: 2
  ci:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - main
                - trunk
                - /feature\/.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - main
                - trunk
